### PR TITLE
Added NN protobufs

### PR DESCRIPTION
**Pull request by omiguelc**

### CODE REVIEW

**Comment by aloeliger** [comment]
+l1

**Comment by aloeliger** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

only new data files so it is safe to merge but better to get it merged with https://github.com/cms-sw/cmssw/pull/43766 (which requires these new data files)

**Comment by rappoccio** [comment]
+1

**Comment by rappoccio** [comment]
merge

**Pull request merged**
